import type { CapabilityInventoryEntry, CapabilityOwner } from "./model.ts"
import { normalizeIdSegment } from "./model.ts"

interface ManualDefinition {
  id: string
  name?: string
  kind?: string
  description: string
  anchor?: string
  parent?: string
  metadata?: Record<string, unknown>
}

const owners = {
  dom: { repository: "renderer", package: "@zavx0z/dom", stage: "semantic" },
  core: { repository: "renderer", package: "@zavx0z/renderer", stage: "cpu" },
  browser: { repository: "renderer", package: "@zavx0z/renderer-browser", stage: "browser-host" },
  webgpu: { repository: "renderer", package: "@zavx0z/renderer-webgpu", stage: "webgpu" },
  react: { repository: "renderer", package: "@zavx0z/react", stage: "authoring-runtime" },
  devtools: { repository: "renderer", package: "@zavx0z/dom-devtools", stage: "inspection" },
  template: { repository: "template", package: "@zavx0z/template", stage: "compiler" },
  engine: { repository: "engine", package: "@engine/core", stage: "gpu-scene-resource" },
} satisfies Record<string, CapabilityOwner>

export function buildManualInventories(): CapabilityInventoryEntry[] {
  return [
    ...manual(
      "dom",
      "dom.algorithms",
      "whatwg-dom",
      "commit a2331a45360129e8645ef7e0a04740241b6e3726",
      "standard",
      owners.dom,
      domAlgorithms,
    ),
    ...manual(
      "html",
      "html.behaviors",
      "whatwg-html",
      "commit 4aa7694b585e4d551a11cfe6dece823105fdf0a8",
      "standard",
      owners.dom,
      htmlBehaviors,
    ),
    ...manual(
      "css",
      "css.features",
      "css-snapshot-2025",
      "W3C Group Note 2025-09-18 + WebRef CSS 8.7.3",
      "standard",
      owners.core,
      cssFeatures,
    ),
    ...manual(
      "react",
      "react.semantics",
      "react-docs-19.2",
      "19.2",
      "reference",
      owners.react,
      reactSemantics,
    ),
    ...manual(
      "tsx",
      "tsx.typescript",
      "typescript-jsx",
      "TypeScript 7.0.2",
      "reference",
      owners.template,
      typescriptJsxFeatures,
    ),
    ...manual(
      "tsx",
      "tsx.tagged-html",
      "template-contract",
      "@zavx0z/template 2.6.2 at 87d0ec3d2a9f19c3750d567ee20dc4bace995e90",
      "project-contract",
      owners.template,
      taggedHtmlFeatures,
    ),
    ...manual(
      "tsx",
      "tsx.compiler",
      "template-contract",
      "@zavx0z/template 2.6.2 at 87d0ec3d2a9f19c3750d567ee20dc4bace995e90",
      "project-contract",
      owners.template,
      tsxCompilerFeatures,
    ),
    ...manual(
      "renderer",
      "renderer.features",
      "renderer-contract",
      "renderer 3c91038c3f14ccc44616209fd82b1e59b7369408",
      "project-contract",
      owners.core,
      rendererFeatures,
    ),
    ...manual(
      "browser",
      "browser.features",
      "renderer-browser-contract",
      "renderer 3c91038c3f14ccc44616209fd82b1e59b7369408",
      "project-contract",
      owners.browser,
      browserFeatures,
    ),
    ...manual(
      "webgpu",
      "webgpu.features",
      "renderer-webgpu-contract",
      "renderer 3c91038c3f14ccc44616209fd82b1e59b7369408",
      "project-contract",
      owners.webgpu,
      webgpuFeatures,
    ),
    ...manual(
      "devtools",
      "devtools.features",
      "dom-devtools-contract",
      "renderer 3c91038c3f14ccc44616209fd82b1e59b7369408",
      "project-contract",
      owners.devtools,
      devtoolsFeatures,
    ),
    ...manual(
      "engine",
      "engine.features",
      "engine-core-contract",
      "engine 18c55d6c3dc68d1f2ab257378a505e5bac2eea3e",
      "project-contract",
      owners.engine,
      engineFeatures,
    ),
  ]
}

function manual(
  domain: string,
  prefix: string,
  source: string,
  version: string,
  profile: "standard" | "reference" | "project-contract",
  ownerHint: CapabilityOwner,
  definitions: ManualDefinition[],
): CapabilityInventoryEntry[] {
  return definitions.map((definition) => ({
    id: `${prefix}.${definition.id}`,
    domain,
    kind: definition.kind ?? "behavior",
    name: definition.name ?? definition.id.replaceAll("-", " "),
    description: definition.description,
    ...(definition.parent ? { parent: `${prefix}.${definition.parent}` } : {}),
    spec: {
      source,
      version,
      anchor: definition.anchor ?? `${source}#${normalizeIdSegment(definition.id)}`,
      profile,
    },
    ownerHint,
    ...(definition.metadata ? { metadata: definition.metadata } : {}),
  }))
}

const domAlgorithms: ManualDefinition[] = [
  { id: "one-semantic-tree", description: "A Document owns one observable semantic node tree and one identity per Node." },
  { id: "interface-object-construction", description: "Interface objects, constructors, prototype identity, and illegal construction rules." },
  { id: "event-listener-registration", description: "EventTarget listener registration, removal, identity, once, capture, and passive options." },
  { id: "event-dispatch-path", description: "Construct the exact event path through semantic ancestors." },
  { id: "event-capture-phase", description: "Invoke capture listeners from root toward target." },
  { id: "event-target-phase", description: "Invoke target listeners with observable target/currentTarget/phase." },
  { id: "event-bubble-phase", description: "Invoke bubbling listeners from target parent toward root." },
  { id: "event-cancellation", description: "Cancelable events, preventDefault, passive behavior, and dispatch return value." },
  { id: "event-propagation-stop", description: "stopPropagation and stopImmediatePropagation semantics." },
  { id: "tree-pre-insertion-validity", description: "Reject tree insertions that violate hierarchy and cycle invariants." },
  { id: "tree-insert", description: "Insert nodes while preserving parent, sibling, ownership, and mutation observability." },
  { id: "document-fragment-splicing", description: "Insert a fragment's children rather than the fragment itself." },
  { id: "tree-remove", description: "Remove a node and update observable tree relations and connected state." },
  { id: "tree-replace", description: "Replace one or more children atomically according to DOM rules." },
  { id: "node-adoption", description: "Adopt cross-Document subtrees and update ownerDocument recursively." },
  { id: "node-connected-state", description: "Compute isConnected from the current Document tree." },
  { id: "node-clone-import", description: "Clone and import nodes with the specified depth and ownership semantics." },
  { id: "node-normalize", description: "Merge adjacent Text nodes and remove empty Text nodes." },
  { id: "text-content", description: "Read and replace textContent across Node kinds." },
  { id: "parent-node-mixins", description: "ParentNode query and mutation algorithms." },
  { id: "child-node-mixins", description: "ChildNode before/after/replaceWith/remove algorithms." },
  { id: "live-collections", description: "Live NodeList and HTMLCollection identity and update behavior." },
  { id: "attribute-storage", description: "Attribute creation, replacement, removal, order, and observable identity." },
  { id: "namespaces", description: "Namespace-aware elements, attributes, lookup, and qualified names." },
  { id: "selectors", description: "Selectors API matching, closest, querySelector, and querySelectorAll." },
  { id: "tree-traversal", description: "NodeIterator and TreeWalker traversal with filters." },
  { id: "range-boundaries", description: "Range boundary points, mutation adjustment, extraction, cloning, and geometry boundary." },
  { id: "selection", description: "Document selection identity, ranges, direction, and mutation behavior." },
  { id: "mutation-observer", description: "MutationObserver queues, transient observers, record coalescing, and microtask delivery." },
  { id: "parsing-boundary", description: "DOM parsing entrypoints and fragment parsing ownership." },
  { id: "serialization-boundary", description: "DOM and HTML serialization entrypoints." },
  { id: "shadow-tree", description: "ShadowRoot creation, encapsulated tree identity, and composed-tree behavior." },
  { id: "slot-assignment", description: "Slot assignment, flattening, slotchange, and assigned node APIs." },
  { id: "custom-elements", description: "Custom element registry, definition, upgrade, lifecycle callbacks, and reactions." },
  { id: "element-internals", description: "ElementInternals form, state, shadow, and accessibility surface." },
  { id: "focus", description: "Focusable area ownership, activeElement, focus/blur, and focus event sequence." },
  { id: "pointer-capture", description: "Pointer capture ownership, pending override, got/lost events, and release." },
]

const htmlBehaviors: ManualDefinition[] = [
  { id: "attribute-property-reflection", description: "Content attributes reflect through the matching IDL properties with specified coercion." },
  { id: "live-state-vs-content-attributes", description: "Dirty/live control state remains distinct from default content attributes." },
  { id: "content-categories", description: "Element categories are represented where they affect observable behavior." },
  { id: "content-model", description: "Element content-model constraints and parser/DOM effects." },
  { id: "default-actions", description: "Trusted activation and input events run the element's specified default action." },
  { id: "activation-behavior", description: "Legacy pre-activation, activation, and canceled activation behavior." },
  { id: "disabledness", description: "Direct and inherited disabledness suppresses activation and focus as specified." },
  { id: "focusability", description: "Element and control focusability follows HTML rules." },
  { id: "sequential-focus-navigation", description: "tabindex and document order determine sequential navigation." },
  { id: "hidden", description: "hidden state affects rendering and interaction without destroying semantic identity." },
  { id: "inert", description: "inert subtrees suppress focus, activation, selection, and accessibility exposure." },
  { id: "label-association", description: "Explicit and implicit labels resolve to labelable controls." },
  { id: "form-ownership", description: "Listed controls resolve and update their form owner." },
  { id: "constraint-validation", description: "ValidityState, validation messages, willValidate, checkValidity, and reportValidity." },
  { id: "form-reset", description: "Form reset restores control defaults and dispatches the reset event." },
  { id: "form-submission", description: "Submission constructs form data, validates, dispatches submit/formdata, and navigates or invokes actions." },
  ...[
    "hidden", "text", "search", "tel", "url", "email", "password", "date", "month", "week",
    "time", "datetime-local", "number", "range", "color", "checkbox", "radio", "file", "submit",
    "image", "reset", "button",
  ].map((type) => ({
    id: `input-type-${type}`,
    name: `input type=${type}`,
    kind: "input-type",
    description: `HTMLInputElement ${type} state, sanitization, properties, events, and activation behavior.`,
    anchor: `https://html.spec.whatwg.org/multipage/input.html#${normalizeIdSegment(type)}-state-(type=${type})`,
  })),
  { id: "input-selection", description: "Text-like input selectionStart, selectionEnd, selectionDirection, and range mutation." },
  { id: "input-step", description: "stepUp and stepDown apply type-specific stepping, ranges, and mismatch rules." },
  { id: "input-picker", description: "showPicker invokes the type-specific picker with activation and security checks." },
  { id: "textarea", description: "Textarea raw/default/live value, wrapping, selection, and validation semantics." },
  { id: "select-option-optgroup", description: "Select, option, and optgroup ownership, live collections, selectedness, and picker/listbox behavior." },
  { id: "button", description: "Button type, disabledness, command, submit, and reset activation semantics." },
  { id: "progress-meter", description: "Progress and meter numeric normalization and semantic rendering state." },
  { id: "lists", description: "Ordered/unordered/description list semantic state and reflected attributes." },
  { id: "tables", description: "Table model, rows/cells/sections collections, spans, headers, and algorithms." },
  { id: "images", description: "Image request selection, decode, dimensions, currentSrc, load/error, and fallback semantics." },
  { id: "media", description: "Audio/video resource selection, playback state, tracks, events, and controls." },
  { id: "canvas", description: "Canvas bitmap, contexts, dimensions, serialization, and transfer semantics." },
  { id: "dialog", description: "Dialog modal/nonmodal state, top layer, focus, close request, and events." },
  { id: "popover", description: "Popover state, top layer, invokers, light dismiss, focus, and toggle events." },
  { id: "details-summary", description: "Details disclosure state, summary activation, exclusivity, and toggle events." },
  { id: "links-navigation", description: "Hyperlink activation, URL resolution, target, download, ping, and navigation." },
  { id: "editing", description: "contenteditable, designMode, editing host, selection, and input mutation behavior." },
  { id: "clipboard", description: "Clipboard events and async clipboard integration at editing and input boundaries." },
  { id: "drag-and-drop", description: "Drag data store, DataTransfer, event sequence, cancellation, and drop behavior." },
  { id: "resource-loading", description: "Element-owned fetch, readiness, cancellation, and resource lifecycle." },
  { id: "load-error-events", description: "Resource owners dispatch load/error with the specified timing and target." },
  { id: "accessibility-semantics", description: "Implicit roles, allowed ARIA, accessible names/states, and platform mappings." },
]

const cssFeatures: ManualDefinition[] = [
  ...[
    "syntax", "tokenization", "declarations", "component-values", "data-types", "functions", "units",
    "selectors", "combinators", "pseudo-classes", "pseudo-elements", "specificity", "cascade",
    "cascade-origins", "cascade-order", "inheritance", "initial", "revert", "revert-layer", "unset",
    "custom-properties", "cascade-layers", "scope", "nesting", "at-rules", "descriptors", "media-queries",
    "supports-queries", "container-queries", "longhands", "shorthands", "logical-properties", "writing-modes",
    "box-model", "sizing", "block-layout", "inline-layout", "flex-layout", "grid-layout", "table-layout",
    "floats", "positioning", "fragmentation", "multicol", "containment", "overflow", "scrolling",
    "scrollbars", "clipping", "stacking-contexts", "z-index", "transforms", "transform-origins", "colors",
    "backgrounds", "borders", "radii", "shadows", "filters", "masks", "opacity", "images",
    "replaced-content", "object-fit", "object-position", "fonts", "text", "white-space", "wrapping",
    "line-breaking", "text-overflow", "generated-content", "counters", "transitions", "animations", "cssom",
    "computed-values", "used-values", "display-list-projection", "hit-test-projection", "webgpu-transport",
  ].map((id) => ({ id, kind: "css-algorithm", description: `CSS ${id.replaceAll("-", " ")} semantics from the pinned CSS profile.` })),
]

const reactSemantics: ManualDefinition[] = [
  ...([
    ["function-components", "Function component invocation, props, identity, and update semantics."],
    ["class-components", "Class component construction, lifecycle, state, and error semantics."],
    ["nested-components", "Nested component ownership and independent lifecycle."],
    ["component-identity", "Component identity follows type, parent position, and key."],
    ["props", "Props delivery and immutability model."],
    ["default-props", "Default props compatibility behavior."],
    ["children", "Opaque children model and component children delivery."],
    ["keys", "Keyed identity and reconciliation behavior."],
    ["callback-refs", "Callback ref attach, detach, and cleanup semantics."],
    ["object-refs", "Object ref current mutation semantics."],
    ["fragments", "Fragment grouping without an extra host node."],
    ["memo", "Memoized component comparison and bailout."],
    ["lazy", "Lazy component loading and suspension behavior."],
    ["forward-ref", "Ref forwarding compatibility API."],
    ["context", "Context creation, provider lookup, consumer reads, and update propagation."],
    ["create-element", "React element creation API."],
    ["clone-element", "React element clone API."],
    ["is-valid-element", "React element identity predicate."],
    ["children-api", "Children map, forEach, count, only, and toArray APIs."],
    ["strict-mode", "StrictMode development checks and replay behavior."],
    ["suspense", "Suspension boundary fallback and reveal behavior."],
    ["error-boundaries", "Render/lifecycle error isolation by class boundaries."],
    ["portals", "Portal ownership and event semantics across host containers."],
    ["hydration", "Attach to server-rendered host content with mismatch behavior."],
    ["server-rendering", "Server rendering and streaming APIs."],
    ["server-components", "React Server Component reference model."],
    ["directives-actions", "React directives, actions, and form action model."],
    ["create-root", "Client root construction and ownership."],
    ["render-update", "Root render and update scheduling."],
    ["unmount", "Root teardown, cleanup, and host removal."],
    ["batching", "Batch updates and observable commit boundaries."],
    ["scheduling", "Priority and scheduler behavior."],
    ["render-phase-updates", "Render-phase update limits and restart semantics."],
    ["commit-phases", "Insertion, mutation, layout, and passive commit phase ordering."],
    ["cleanup", "Effect/ref/subscription cleanup ordering."],
    ["failed-render-isolation", "Failed render rollback without partial host mutation."],
    ["strict-mode-replay", "Development replay of render and effects."],
    ["concurrency", "Interruptible and concurrent rendering reference behavior."],
    ["transitions", "Transition scheduling and pending state."],
    ["browser-execution-evidence", "Execution in an actual browser host, distinct from bundle generation."],
    ["architecture-react-package-alias", "Whether @zavx0z/react is the npm react package or alias."],
    ["architecture-npm-react-dependency", "Whether npm react is a dependency."],
    ["architecture-fiber", "Whether Fiber is present."],
    ["architecture-virtual-dom", "Whether a persistent virtual DOM is present."],
    ["architecture-react-dom-host", "Whether react-dom owns host rendering."],
    ["conditional-ranges", "Compiled conditional child ranges."],
    ["custom-hooks", "Governed custom hooks in compiled components."],
    ["context-consumer", "JSX Context.Consumer compatibility surface."],
    ["jsx-context-provider", "JSX context provider compatibility surface."],
    ["low-level-context-providers", "Project low-level provideContext composition API."],
    ["debug-value-inspection", "Inspection exposure for useDebugValue."],
    ["effect-event-callsite-validation", "Reference callsite restrictions for Effect Events."],
    ["governed-react-imports", "Whether authored npm React imports are admitted by the compiler."],
    ["template-compiler-abi", "Fixed-slot Template compiler ABI integration."],
    ["template-compiler-integration", "End-to-end compiled Template to @zavx0z/react host integration."],
    ["compiler-export", "Whether compiler APIs are exported by @zavx0z/react."],
    ["tsx-authoring", "Governed TSX authoring profile."],
    ["browser-target-build", "Browser-target bundle generation."],
    ["browser-execution", "Actual browser execution acceptance."],
    ["gpu-instancing", "Whether GPU instancing is part of the @zavx0z/react compatibility contract."],
    ["passive-paint-scheduling", "React-like passive effect scheduling after browser paint."],
    ["server-external-store-snapshots", "Server snapshot behavior for useSyncExternalStore."],
    ["source-maps", "Authored TSX source maps through the Template compiler."],
    ["static-template-identity", "Stable compiled static template identity."],
    ["strict-mode-effect-replay", "StrictMode development effect replay."],
  ] as const).map(([id, description]) => ({ id, kind: "reference-semantics", description })),
]

const typescriptJsxFeatures: ManualDefinition[] = [
  { id: "tsx-file-syntax", description: ".tsx files accept JSX grammar when the jsx compiler option is enabled." },
  { id: "intrinsic-elements", description: "Lowercase JSX names resolve through JSX.IntrinsicElements." },
  { id: "value-elements", description: "Uppercase JSX names resolve as value-based component expressions." },
  { id: "jsx-namespace", description: "JSX namespace controls element, attributes, children, and component typing." },
  { id: "attribute-type-checking", description: "JSX attributes are checked against intrinsic or component props." },
  { id: "children-type-checking", description: "JSX children are checked through ElementChildrenAttribute and props." },
  { id: "expression-children", description: "JavaScript expressions may appear in JSX children." },
  { id: "spread-attributes", description: "JSX supports spread attributes in the syntax and typing model." },
  { id: "fragments", description: "JSX fragment syntax is supported by TypeScript emit modes." },
  { id: "namespaced-names", description: "JSX namespaced element and attribute syntax model." },
  { id: "generic-components", description: "Generic value-based components participate in JSX type inference." },
  { id: "automatic-runtime", description: "react-jsx emit imports jsx/jsxs/Fragment from jsx-runtime." },
  { id: "development-runtime", description: "react-jsxdev emit imports jsxDEV/Fragment from jsx-dev-runtime." },
  { id: "classic-runtime", description: "Classic JSX emit calls the configured JSX factory." },
  { id: "source-maps", description: "Compiler output can map generated code to authored TSX locations." },
  { id: "angle-bracket-assertion-rejection", description: "Angle-bracket type assertions are rejected in .tsx files." },
]

const taggedHtmlFeatures: ManualDefinition[] = [
  ...([
    ["static-element-names", "Static element names."],
    ["dynamic-values", "Dynamic primitive and object values."],
    ["attributes", "Static and dynamic attributes."],
    ["boolean-remove-semantics", "Boolean, nullish, and removal semantics."],
    ["events", "Dynamic event listener binding and disposal."],
    ["nested-templates", "Nested template identity and bounded replacement."],
    ["arrays", "Array child reconciliation."],
    ["positional-reconciliation", "Surviving positional child identity."],
    ["keyed-behavior", "Keyed child movement and identity."],
    ["comments", "HTML comments."],
    ["raw-text-elements", "script/style/textarea/title raw-text parsing."],
    ["doctypes", "Doctype and declaration parsing."],
    ["dynamic-tags", "Dynamic tag names."],
    ["disposal", "Listener and mounted region disposal."],
    ["transaction-boundaries", "One observable mutation transaction per mount/update/dispose."],
    ["failure-rollback", "Failed update rollback without partial DOM mutation."],
    ["security-injection", "Dynamic strings remain text/attribute data and cannot inject markup."],
    ["namespace-tags", "Namespace-qualified element construction."],
  ] as const).map(([id, description]) => ({ id, kind: "tagged-html", description })),
]

const tsxCompilerFeatures: ManualDefinition[] = [
  ...[
    "intrinsic-elements", "function-components", "nested-components", "props", "children", "primitive-children",
    "component-children", "arrays", "map", "keys", "conditional-branches", "fragments", "refs", "callback-refs",
    "object-refs", "event-bindings", "event-capture-bindings", "property-bindings", "style-bindings", "spreads",
    "dynamic-tags", "namespace-tags", "class", "class-name", "explicit-children-prop", "destructured-receivers",
    "generic-components", "source-roots", "dependency-invalidation", "symbol-resolution", "compiler-diagnostics",
    "semantic-diagnostics", "source-maps", "browser-target-build", "runtime-jsx-fail-closed", "root-render",
    "memo-components", "keyed-component-map", "multiple-keyed-children", "custom-hooks", "hook-order-validation",
    "react-import-rejection", "dynamic-import-rejection", "dangerously-set-inner-html-rejection", "async-component-rejection",
    "arrow-component-rejection", "early-return-rejection", "component-escape-rejection", "fixed-slot-abi",
    "binding-range-validation", "binding-realm-validation", "same-parent-anchor-validation",
    "static-style-extraction",
  ].map((id) => ({ id, kind: "tsx-compiler", description: `Template compiler support boundary for ${id.replaceAll("-", " ")}.` })),
]

const rendererFeatures: ManualDefinition[] = [
  ...[
    "stylesheet-parser", "selector-matching", "specificity", "cascade", "computed-style", "inheritance", "block-layout",
    "inline-layout", "flex-layout", "sizing", "box-model", "positioning", "overflow", "clip-stacks", "scroll-metrics",
    "scrollbar-paint", "typography", "line-breaking", "images", "form-control-projection", "progress-meter",
    "textarea-select-range", "z-index", "transforms", "shadows", "display-list", "hit-metadata", "invalidation",
    "incremental-patches", "tooltip-title", "pointer", "wheel", "default-activation", "popover-projection",
    "immutable-frame", "clean-frame-fast-path", "text-leaf-fast-path", "transform-subtree-fast-path", "performance-paths",
    "projection-root-inheritance",
    "compiled-stylesheet-lifecycle",
    "caret-selection-paint", "vector-path-display-item", "geometry-readback", "backend-neutral-diagnostics",
  ].map((id) => ({ id, kind: "renderer-stage", description: `CPU Renderer ${id.replaceAll("-", " ")} capability.` })),
]

const browserFeatures: ManualDefinition[] = [
  ...[
    "canvas-lifecycle", "viewport", "resize", "device-pixel-ratio", "pointer-mapping", "wheel", "pointer-capture",
    "semantic-pointer-events", "text-input-proxy", "textarea-proxy", "keyboard", "beforeinput-input", "composition-ime",
    "selection-synchronization", "cancellation-rollback", "capture", "document-plane", "multiple-planes", "overlays",
    "camera-gestures", "cleanup", "error-boundaries", "lifecycle-boundaries", "animation-frame-coalescing",
    "native-browser-evidence", "same-document-input-identity", "number-input-proxy", "select-picker", "clipboard-proxy",
    "one-experience-topology", "direct-world-regions",
    "compiled-stylesheet-scheduling",
  ].map((id) => ({ id, kind: "browser-host", description: `Browser composition ${id.replaceAll("-", " ")} capability.` })),
]

const webgpuFeatures: ManualDefinition[] = [
  ...[
    "frame-validation", "rect", "text", "image", "colors", "borders", "radii", "shadows", "transforms", "clipping",
    "scalar-retained-path", "automatic-rect-instancing", "run-barriers", "overlap-law", "stable-slots",
    "partial-record-uploads", "paint-order", "texture-readiness", "cleanup", "geometry-invalidation", "diagnostics",
    "unsupported-combinations", "screen-overlay", "document-plane", "device-pixel-evidence", "resource-lifetime",
    "vector-path",
  ].map((id) => ({ id, kind: "webgpu-backend", description: `Retained WebGPU backend ${id.replaceAll("-", " ")} capability.` })),
]

const devtoolsFeatures: ManualDefinition[] = [
  ...[
    "document-inspector", "stable-node-ids", "subtree-snapshots", "mutation-notifications", "state-notifications",
    "renderer-projection", "hit-projection", "display-key-projection", "deep-frozen-json", "reverse-reference-release",
    "disposal", "css-panel", "editing", "transport", "engine-resource-inspection", "react-devtools-integration",
  ].map((id) => ({ id, kind: "inspection", description: `DOM inspection ${id.replaceAll("-", " ")} capability.` })),
]

const engineFeatures: ManualDefinition[] = [
  ...[
    "scene-graph", "transforms", "world-transform-update", "geometry", "buffer-attributes", "dirty-intervals", "materials",
    "analytical-ui-materials", "instance-layer", "instanced-rounded-rectangles", "draw-range-views", "text", "font-loading",
    "glyph-cache-identity", "texture-image-loading", "texture-device-identity", "clipping", "ray-casting", "culling",
    "view-point", "space", "webgpu-pipelines", "resource-lifetime", "renderer-disposal", "capture-readback", "loaders",
    "gltf", "animation", "public-math", "index-buffer-format", "material-groups", "device-loss", "gpu-device-evidence",
    "dom-css-ownership-boundary", "browser-document-boundary", "legacy-ui-display-flag", "clip-surface-unification",
    "bounded-multi-view-frame",
  ].map((id) => ({ id, kind: "engine-contract", description: `Engine ${id.replaceAll("-", " ")} capability.` })),
]
